### ISSUE TITLE
Not able to publish via command

### ISSUE THREAD

**Issue by mahesh-rajawat** [renatocason/magento2-module-mq#11]
You have not given any publish command example.
i am trying like this:
![screenshot_29](https://user-images.githubusercontent.com/32479280/50214303-efd96600-03a5-11e9-90d4-2621ba209019.png)

**Comment by renatocason** [comment]
Hi @maheshWebkul721 ,

I'm sorry there is no example about that command, it's meant to be more like a testing/debugging helper. Since the message might also be an object, the command requires it to be json encoded.

For instance, with the [example module](https://github.com/renatocason/magento2-module-mq-example) you would execute:
`bin/magento ce_mq:messages:publish product.updates 1`

In your case, if the message is expected to be a string, just adding double quotes will make it a valid json:
`bin/magento ce_mq:messages:publish generate.sitemaps "product"`

In case you need a complex object, it should look like:
`bin/magento ce_mq:messages:publish generate.sitemaps '{"product":{"id":1}}'`

Hope that helps!

Regards,
Renato

**Comment by mahesh-rajawat** [comment]
@renatocason , Message content as Json format is working fine that's what i need. Thanks for it.
But as you mentioned on second steps is still not working

![bbzitdjnqumbljh-madwea](https://user-images.githubusercontent.com/32479280/50268766-ffae8400-0451-11e9-98cb-e76a115bfb44.png)

**Comment by renatocason** [comment]
Hi @maheshWebkul721 ,

Sorry for that, I didn't actually check the command setting the _messageSchema_ as _string_.
It looks like the console library is stripping away the double quotes, so the parameter should be itself wrapped in single quotes. I tested that and it works, in your case it would be:
`bin/magento ce_mq:messages:publish generate.sitemaps '"product"'`

Let me know if that works for you as well!

Renato

**Comment by mahesh-rajawat** [comment]
@renatocason , Thanks its working now.

**Comment by renatocason** [comment]
Amazing @maheshWebkul721 , thanks for letting me know!
Closing this for now, if you have any further question feel free to reopen.
