### ISSUE TITLE
Command "queue:consumers:start" is not defined in Magento version 2.3.x

### ISSUE THREAD

**Issue by Tomasz-Silpion** [renatocason/magento2-module-mq#19]
This topic is directly related to #12 

_Rcason_Mq_ modules were a great thing up to Magento 2.3 but seems to conflict somehow with last Magento 2 editions causing new queue:consumers:start command from _\Magento\MessageQueue\Console\StartConsumerCommand_ class not to run leaving following info in _system.log_ with each CRON execution:

```
[2020-04-25 22:39:08] main.ERROR: Command "queue:consumers:start" is not defined.

Did you mean one of these?
    ce_mq:consumers:start
    queue:consumers:list
#0 /home/magento2/www/vendor/symfony/console/Application.php(226): Symfony\Component\Console\Application->find('queue:consumers...')
#1 /home/magento2/www/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/magento2/www/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/magento2/www/bin/magento(23): Symfony\Component\Console\Application->run()
#4 {main} [] []
[2020-04-25 22:39:08] main.ERROR: Command "queue:consumers:start" is not defined.
````
Did I miss something? I've had to remove:

```
-        "renatocason/magento2-module-mq": "^1.1",
-        "renatocason/magento2-module-mq-amqp": "^1.1",
-        "renatocason/magento2-module-mq-mysql": "^1.2"
```

from composer.json to bring back my Magento 2 instances new, built in operations:

```php
product_action_attribute.update
product_action_attribute.website.update
exportProcessor
codegeneratorProcessor
async.operations.all
```

lack of which caused products exports not to work anymore.

**Comment by renatocason** [comment]
Hi @Tomasz-Silpion ,

Thanks for reporting the issue, I just created a new release (1.1.3) with a fix for it.
The problem was caused by the fact that both this and the core module used the same name in the command definitions on di.xml.

Just out of curiosity, are you planning to use this module alongside the core one? If so, is there any particular reason?

Regards,
Renato

**Comment by mlambley** [comment]
We licence our software through a third-party Magento developer who, for their customer, is using the `queue:consumers:start` command for their `product_action_attribute.update`. This was broken until we implemented the 1.1.3 fix.

I don't think it's a matter of "what's your reason for using the original Magento queueing module as well" but rather people have existing systems and are not necessarily going to change the way they do things just because we're doing something different.

**Comment by renatocason** [comment]
Hi @mlambley ,

I never said it was "a matter of". In fact, I first fixed the issue and then asked the question.
And if that wasn't enough, I also wrote very clearly that it was just a curiosity.

**Comment by mlambley** [comment]
You asked a question, and I answered. All is well, friend.
